# Generated by Django 5.0.6 on 2024-07-04 03:51

import API.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_bankaccount_account_delete_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='account',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default=API.utils.generate_account_number, max_length=8, unique=True),
        ),
    ]
