# Generated by Django 5.0.6 on 2024-07-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_blog_alter_bankaccount_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
