# Generated by Django 5.0.6 on 2024-07-25 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='API.bankaccount'),
        ),
    ]
