# Generated by Django 5.0.6 on 2024-08-02 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_transaction_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
